-- ============================================================
-- Parts Catalog — Supabase schema
-- Run this once in your Supabase project: SQL Editor → New query → paste → Run
-- ============================================================

-- ---------- Tables ----------

create table if not exists brands (
  id bigint generated always as identity primary key,
  name_en text not null,
  name_ka text not null
);

create table if not exists categories (
  id bigint generated always as identity primary key,
  name_en text not null,
  name_ka text not null
);

create table if not exists parts (
  id bigint generated always as identity primary key,
  code text not null unique,
  title_en text not null,
  title_ka text not null,
  description_en text default '',
  description_ka text default '',
  brand_id bigint references brands(id) on delete set null,
  category_id bigint references categories(id) on delete set null,
  image_path text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_parts_code on parts(code);
create index if not exists idx_parts_brand on parts(brand_id);
create index if not exists idx_parts_category on parts(category_id);

-- Keep updated_at fresh automatically
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists parts_updated_at on parts;
create trigger parts_updated_at
  before update on parts
  for each row execute function set_updated_at();

-- ---------- Row Level Security ----------
-- Public (anon key) can READ everything.
-- Only a signed-in user (your one admin account) can WRITE.

alter table brands enable row level security;
alter table categories enable row level security;
alter table parts enable row level security;

drop policy if exists "Public read brands" on brands;
create policy "Public read brands" on brands for select using (true);

drop policy if exists "Authenticated write brands" on brands;
create policy "Authenticated write brands" on brands for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "Public read categories" on categories;
create policy "Public read categories" on categories for select using (true);

drop policy if exists "Authenticated write categories" on categories;
create policy "Authenticated write categories" on categories for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "Public read parts" on parts;
create policy "Public read parts" on parts for select using (true);

drop policy if exists "Authenticated write parts" on parts;
create policy "Authenticated write parts" on parts for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- ---------- Storage bucket for part photos ----------

insert into storage.buckets (id, name, public)
values ('part-images', 'part-images', true)
on conflict (id) do nothing;

drop policy if exists "Public read part images" on storage.objects;
create policy "Public read part images" on storage.objects
  for select using (bucket_id = 'part-images');

drop policy if exists "Authenticated upload part images" on storage.objects;
create policy "Authenticated upload part images" on storage.objects
  for insert with check (bucket_id = 'part-images' and auth.role() = 'authenticated');

drop policy if exists "Authenticated update part images" on storage.objects;
create policy "Authenticated update part images" on storage.objects
  for update using (bucket_id = 'part-images' and auth.role() = 'authenticated');

drop policy if exists "Authenticated delete part images" on storage.objects;
create policy "Authenticated delete part images" on storage.objects
  for delete using (bucket_id = 'part-images' and auth.role() = 'authenticated');


-- ====================================================
-- Complete Supabase Seed SQL for All 83 Mercedes Parts
-- ====================================================

insert into brands (id, name_en, name_ka) values (1, 'Mercedes-Benz', 'მერსედეს-ბენცი') on conflict (id) do nothing;

insert into categories (id, name_en, name_ka) values
  (1, 'Headlight Modules', 'ფარების მოდულები'),
  (2, 'Digital Light Modules', 'Digital Light მოდულები'),
  (3, 'Sensors & Radars', 'სენსორები და რადარები'),
  (4, 'DRL & LED Diodes', 'დღის განათების დიოდები'),
  (5, 'Voltage Converters', 'ძაბვის გარდამქმნელები'),
  (6, 'Xenon & Ballast Units', 'ქსენონის მოდულები')
on conflict (id) do nothing;

insert into parts (code, title_en, title_ka, description_en, description_ka, brand_id, category_id, image_path) values
  ('A0009052504', 'Mercedes W205 / W213 / W222 / X253 Distronic Radar Distance Sensor Module', 'მერსედეს W205 / W213 / W222 / X253 დისტრონიკის მანძილის რადარის სენსორი', 'Original OEM Mercedes-Benz Distronic Radar Distance Sensor Module for W205 / W213 / W222 / X253. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის დისტრონიკის მანძილის რადარის სენსორი (W205 / W213 / W222 / X253). გარანტირებული ხარისხი და თავსებადობა.', 1, 3, '/parts/0009052504.webp'),
  ('A0009052804', 'Mercedes W205 / W213 / W222 / C238 Radar Sensor Distronic Control Unit', 'მერსედეს W205 / W213 / W222 / C238 დისტრონიკის რადარის მართვის ბლოკი', 'Original OEM Mercedes-Benz Radar Sensor Distronic Control Unit for W205 / W213 / W222 / C238. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის დისტრონიკის რადარის მართვის ბლოკი (W205 / W213 / W222 / C238). გარანტირებული ხარისხი და თავსებადობა.', 1, 3, '/parts/0009052804.webp'),
  ('A0009054101', 'Mercedes W177 / W205 / W213 / X253 Blind Spot Radar Sensor Module', 'მერსედეს W177 / W205 / W213 / X253 მკვდარი ზონის (Blind Spot) რადარის სენსორი', 'Original OEM Mercedes-Benz Blind Spot Radar Sensor Module for W177 / W205 / W213 / X253. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის მკვდარი ზონის (Blind Spot) რადარის სენსორი (W177 / W205 / W213 / X253). გარანტირებული ხარისხი და თავსებადობა.', 1, 3, '/parts/000905411.webp'),
  ('A0009054603', 'Mercedes W177 / C118 / W205 / W213 Side Assist Blind Spot Radar Unit', 'მერსედეს W177 / C118 / W205 / W213 გვერდითი მკვდარი ზონის სენსორის მოდული', 'Original OEM Mercedes-Benz Side Assist Blind Spot Radar Unit for W177 / C118 / W205 / W213. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის გვერდითი მკვდარი ზონის სენსორის მოდული (W177 / C118 / W205 / W213). გარანტირებული ხარისხი და თავსებადობა.', 1, 3, '/parts/0009054603.webp'),
  ('A0009054907', 'Mercedes W205 / W213 / W222 / X253 Radar Sensor Control Computer', 'მერსედეს W205 / W213 / W222 / X253 რადარის სენსორების მართვის კომპიუტერი', 'Original OEM Mercedes-Benz Radar Sensor Control Computer for W205 / W213 / W222 / X253. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის რადარის სენსორების მართვის კომპიუტერი (W205 / W213 / W222 / X253). გარანტირებული ხარისხი და თავსებადობა.', 1, 3, '/parts/0009054907.webp'),
  ('A0009055103', 'Mercedes W205 / W213 / X253 / W222 360 Surround View Camera Radar Module', 'მერსედეს W205 / W213 / X253 / W222 360 კამერის და რადარის მართვის მოდული', 'Original OEM Mercedes-Benz 360 Surround View Camera Radar Module for W205 / W213 / X253 / W222. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის 360 კამერის და რადარის მართვის მოდული (W205 / W213 / X253 / W222). გარანტირებული ხარისხი და თავსებადობა.', 1, 3, '/parts/0009055103.webp'),
  ('A0009056911', 'Mercedes W206 / W223 / V167 / X247 Distronic & Surround Camera Control Unit', 'მერსედეს W206 / W223 / V167 / X247 დისტრონიკისა და კამერების მართვის ბლოკი', 'Original OEM Mercedes-Benz Distronic & Surround Camera Control Unit for W206 / W223 / V167 / X247. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის დისტრონიკისა და კამერების მართვის ბლოკი (W206 / W223 / V167 / X247). გარანტირებული ხარისხი და თავსებადობა.', 1, 3, '/parts/0009056911.webp'),
  ('A0009057908', 'Mercedes W205 / W213 / W222 / X253 Collision Avoidance Radar Sensor', 'მერსედეს W205 / W213 / W222 / X253 შეჯახების აცილების რადარის სენსორი', 'Original OEM Mercedes-Benz Collision Avoidance Radar Sensor for W205 / W213 / W222 / X253. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის შეჯახების აცილების რადარის სენსორი (W205 / W213 / W222 / X253). გარანტირებული ხარისხი და თავსებადობა.', 1, 3, '/parts/0009057908.webp'),
  ('A0009058406', 'Mercedes W205 / W213 / X253 / W222 NOX Exhaust Gas Sensor Control Module', 'მერსედეს W205 / W213 / X253 / W222 NOX გამონაბოლქვის სენსორის ბლოკი', 'Original OEM Mercedes-Benz NOX Exhaust Gas Sensor Control Module for W205 / W213 / X253 / W222. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის NOX გამონაბოლქვის სენსორის ბლოკი (W205 / W213 / X253 / W222). გარანტირებული ხარისხი და თავსებადობა.', 1, 3, '/parts/0009058406.webp'),
  ('A0009058802', 'Mercedes W205 / W213 / X253 / W222 Nitrogen Oxide NOX Emissions Sensor', 'მერსედეს W205 / W213 / X253 / W222 აზოტის ჟანგის (NOX) სენსორის მოდული', 'Original OEM Mercedes-Benz Nitrogen Oxide NOX Emissions Sensor for W205 / W213 / X253 / W222. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის აზოტის ჟანგის (NOX) სენსორის მოდული (W205 / W213 / X253 / W222). გარანტირებული ხარისხი და თავსებადობა.', 1, 3, '/parts/0009058802.webp'),
  ('A0009058909', 'Mercedes W205 / W213 / W222 / V167 AdBlue NOX Emission Control Computer', 'მერსედეს W205 / W213 / W222 / V167 AdBlue NOX ემისიების კომპიუტერი', 'Original OEM Mercedes-Benz AdBlue NOX Emission Control Computer for W205 / W213 / W222 / V167. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის AdBlue NOX ემისიების კომპიუტერი (W205 / W213 / W222 / V167). გარანტირებული ხარისხი და თავსებადობა.', 1, 3, '/parts/0009058909.webp'),
  ('A0009059907', 'Mercedes W205 / W213 / X253 / W222 Distronic Plus Front Radar Sensor', 'მერსედეს W205 / W213 / X253 / W222 დისტრონიკ პლუსის წინა რადარი', 'Original OEM Mercedes-Benz Distronic Plus Front Radar Sensor for W205 / W213 / X253 / W222. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის დისტრონიკ პლუსის წინა რადარი (W205 / W213 / X253 / W222). გარანტირებული ხარისხი და თავსებადობა.', 1, 3, '/parts/0009059907.webp'),
  ('A1669003309', 'Mercedes GLE W166 / GLS X166 / GL W166 LED Headlight Control Unit', 'მერსედეს GLE W166 / GLS X166 / GL W166 LED ფარის მართვის მოდული', 'Original OEM Mercedes-Benz LED Headlight Control Unit for GLE W166 / GLS X166 / GL W166. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED ფარის მართვის მოდული (GLE W166 / GLS X166 / GL W166). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/1669003309.webp'),
  ('A1769001204', 'Mercedes A-Class W176 / CLA C117 / GLA X156 LED Headlamp Controller Unit', 'მერსედეს A-Class W176 / CLA C117 / GLA X156 LED ფარის მართვის ბლოკი', 'Original OEM Mercedes-Benz LED Headlamp Controller Unit for A-Class W176 / CLA C117 / GLA X156. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED ფარის მართვის ბლოკი (A-Class W176 / CLA C117 / GLA X156). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/1769001204.webp'),
  ('A1779003803', 'Mercedes A-Class W177 / CLA C118 / GLE V167 Multibeam LED Headlight Computer', 'მერსედეს A-Class W177 / CLA C118 / GLE V167 Multibeam LED ფარის კომპიუტერი', 'Original OEM Mercedes-Benz Multibeam LED Headlight Computer for A-Class W177 / CLA C118 / GLE V167. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Multibeam LED ფარის კომპიუტერი (A-Class W177 / CLA C118 / GLE V167). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/1779003803.webp'),
  ('A2048700126', 'Mercedes C-Class W204 / GLK X204 / E-Class W212 Xenon Ballast Control Unit', 'მერსედეს C-Class W204 / GLK X204 / E-Class W212 ქსენონის ბლოკი და მართვის მოდული', 'Original OEM Mercedes-Benz Xenon Ballast Control Unit for C-Class W204 / GLK X204 / E-Class W212. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის ქსენონის ბლოკი და მართვის მოდული (C-Class W204 / GLK X204 / E-Class W212). გარანტირებული ხარისხი და თავსებადობა.', 1, 6, '/parts/2048700126.webp'),
  ('A2048700326', 'Mercedes C-Class W204 / GLK X204 / E-Class W212 HID Xenon Headlight Ballast Module', 'მერსედეს C-Class W204 / GLK X204 / E-Class W212 HID ქსენონის ფარის ბალასტის მოდული', 'Original OEM Mercedes-Benz HID Xenon Headlight Ballast Module for C-Class W204 / GLK X204 / E-Class W212. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის HID ქსენონის ფარის ბალასტის მოდული (C-Class W204 / GLK X204 / E-Class W212). გარანტირებული ხარისხი და თავსებადობა.', 1, 6, '/parts/2048700326.webp'),
  ('A2059006805', 'Mercedes C-Class W205 Facelift / GLC X253 LED Headlight Control Driver Unit', 'მერსედეს C-Class W205 Facelift / GLC X253 LED ფარის მართვის დრაივერის ბლოკი', 'Original OEM Mercedes-Benz LED Headlight Control Driver Unit for C-Class W205 Facelift / GLC X253. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED ფარის მართვის დრაივერის ბლოკი (C-Class W205 Facelift / GLC X253). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2059006805.webp'),
  ('A2059009534', 'Mercedes C-Class W205 / GLC X253 LED Main Headlamp Control Module', 'მერსედეს C-Class W205 / GLC X253 LED მთავარი ფარის მართვის მოდული', 'Original OEM Mercedes-Benz LED Main Headlamp Control Module for C-Class W205 / GLC X253. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED მთავარი ფარის მართვის მოდული (C-Class W205 / GLC X253). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2059009534.webp'),
  ('A2069007016', 'Mercedes C-Class W206 / S-Class W223 Digital Light Projection Module', 'მერსედეს C-Class W206 / S-Class W223 Digital Light პროექციული ფარის მოდული', 'Original OEM Mercedes-Benz Digital Light Projection Module for C-Class W206 / S-Class W223. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Digital Light პროექციული ფარის მოდული (C-Class W206 / S-Class W223). გარანტირებული ხარისხი და თავსებადობა.', 1, 2, '/parts/2069007016.webp'),
  ('A2129005324', 'Mercedes E-Class W212 Facelift / CLS W218 LED Voltage Converter Control Module', 'მერსედეს E-Class W212 Facelift / CLS W218 LED ძაბვის გარდამქმნელი მოდული', 'Original OEM Mercedes-Benz LED Voltage Converter Control Module for E-Class W212 Facelift / CLS W218. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED ძაბვის გარდამქმნელი მოდული (E-Class W212 Facelift / CLS W218). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2129005324.webp'),
  ('A2129007804', 'Mercedes E-Class W212 Facelift / CLS W218 Full LED Headlight Driver Computer', 'მერსედეს E-Class W212 Facelift / CLS W218 Full LED ფარის დრაივერის კომპიუტერი', 'Original OEM Mercedes-Benz Full LED Headlight Driver Computer for E-Class W212 Facelift / CLS W218. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Full LED ფარის დრაივერის კომპიუტერი (E-Class W212 Facelift / CLS W218). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2129007804.webp'),
  ('A2129008324', 'Mercedes E-Class W212 / CLS-Class W218 LED Headlamp Power Module', 'მერსედეს E-Class W212 / CLS-Class W218 LED ფარის კვების მოდული', 'Original OEM Mercedes-Benz LED Headlamp Power Module for E-Class W212 / CLS-Class W218. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED ფარის კვების მოდული (E-Class W212 / CLS-Class W218). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2129008324.webp'),
  ('A2139000737', 'Mercedes E-Class W213 / C238 / CLS C257 LED Headlight Control Module (Lear PXL3)', 'მერსედეს E-Class W213 / C238 / CLS C257 LED ფარის მოდული (Lear PXL3 star2)', 'Original OEM Mercedes-Benz LED Headlight Control Module (Lear PXL3) for E-Class W213 / C238 / CLS C257. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED ფარის მოდული (Lear PXL3 star2) (E-Class W213 / C238 / CLS C257). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2139000737.webp'),
  ('A2139002334 / A2139002434', 'Mercedes E-Class W213 / CLS C257 Dual Multibeam LED Control Unit Pair', 'მერსედეს E-Class W213 / CLS C257 წყვილი Multibeam LED მართვის ბლოკები', 'Original OEM Mercedes-Benz Dual Multibeam LED Control Unit Pair for E-Class W213 / CLS C257. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის წყვილი Multibeam LED მართვის ბლოკები (E-Class W213 / CLS C257). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2139002334%20%20%202139002434.webp'),
  ('A2139002534 / A2139002634', 'Mercedes E-Class W213 / CLS C257 Multibeam LED Headlight Driver Pair', 'მერსედეს E-Class W213 / CLS C257 Multibeam LED ფარის დრაივერების წყვილი', 'Original OEM Mercedes-Benz Multibeam LED Headlight Driver Pair for E-Class W213 / CLS C257. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Multibeam LED ფარის დრაივერების წყვილი (E-Class W213 / CLS C257). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2139002534%20%202139002634.webp'),
  ('A2139002734 / A2139002834', 'Mercedes E-Class W213 / CLS C257 Multibeam LED Main Headlight Modules', 'მერსედეს E-Class W213 / CLS C257 Multibeam LED მთავარი ფარის მოდულები', 'Original OEM Mercedes-Benz Multibeam LED Main Headlight Modules for E-Class W213 / CLS C257. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Multibeam LED მთავარი ფარის მოდულები (E-Class W213 / CLS C257). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2139002734%20%20%202139002834.webp'),
  ('A2139005035', 'Mercedes E-Class W213 Facelift / CLS C257 Multibeam LED Headlight Computer', 'მერსედეს E-Class W213 Facelift / CLS C257 Multibeam LED ფარის კომპიუტერი', 'Original OEM Mercedes-Benz Multibeam LED Headlight Computer for E-Class W213 Facelift / CLS C257. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Multibeam LED ფარის კომპიუტერი (E-Class W213 Facelift / CLS C257). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2139005035.webp'),
  ('A2139005732 / A2139005832', 'Mercedes E-Class W213 Facelift LED Headlamp Control Unit Pair', 'მერსედეს E-Class W213 Facelift LED ფარის მართვის ბლოკების წყვილი', 'Original OEM Mercedes-Benz LED Headlamp Control Unit Pair for E-Class W213 Facelift. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED ფარის მართვის ბლოკების წყვილი (E-Class W213 Facelift). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2139005732%20%202139005832.webp'),
  ('A2139007206', 'Mercedes E-Class W213 / CLS C257 High-Performance LED Control Unit', 'მერსედეს E-Class W213 / CLS C257 მაღალი წარმადობის LED მოდული', 'Original OEM Mercedes-Benz High-Performance LED Control Unit for E-Class W213 / CLS C257. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის მაღალი წარმადობის LED მოდული (E-Class W213 / CLS C257). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2139007206.webp'),
  ('A2139007208', 'Mercedes E-Class W213 / CLS C257 LED Headlamp Driver Module', 'მერსედეს E-Class W213 / CLS C257 LED ფარის დრაივერის მოდული', 'Original OEM Mercedes-Benz LED Headlamp Driver Module for E-Class W213 / CLS C257. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED ფარის დრაივერის მოდული (E-Class W213 / CLS C257). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2139007208.webp'),
  ('A2139007833 / A2139007933', 'Mercedes E-Class W213 Facelift / C238 Multibeam LED Power Module Pair', 'მერსედეს E-Class W213 Facelift / C238 Multibeam LED კვების მოდულების წყვილი', 'Original OEM Mercedes-Benz Multibeam LED Power Module Pair for E-Class W213 Facelift / C238. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Multibeam LED კვების მოდულების წყვილი (E-Class W213 Facelift / C238). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2139007833%20%202139007933.webp'),
  ('A2139008602', 'Mercedes E-Class W213 / CLS C257 LED Headlight Control Computer', 'მერსედეს E-Class W213 / CLS C257 LED ფარის მართვის კომპიუტერი', 'Original OEM Mercedes-Benz LED Headlight Control Computer for E-Class W213 / CLS C257. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED ფარის მართვის კომპიუტერი (E-Class W213 / CLS C257). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2139008602.webp'),
  ('A2169009100', 'Mercedes CL-Class C216 / S-Class W221 Night View Assist & Headlight Module', 'მერსედეს CL-Class C216 / S-Class W221 ღამის ხედვის ასისტენტის და ფარის მოდული', 'Original OEM Mercedes-Benz Night View Assist & Headlight Module for CL-Class C216 / S-Class W221. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის ღამის ხედვის ასისტენტის და ფარის მოდული (CL-Class C216 / S-Class W221). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2169009100.webp'),
  ('A2189001902', 'Mercedes CLS-Class W218 / E-Class W212 LED Voltage Converter Module', 'მერსედეს CLS-Class W218 / E-Class W212 LED ძაბვის გარდამქმნელი ბლოკი', 'Original OEM Mercedes-Benz LED Voltage Converter Module for CLS-Class W218 / E-Class W212. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED ძაბვის გარდამქმნელი ბლოკი (CLS-Class W218 / E-Class W212). გარანტირებული ხარისხი და თავსებადობა.', 1, 5, '/parts/2189001902.webp'),
  ('A2189004406', 'Mercedes CLS-Class W218 / E-Class W212 Full LED Headlamp Voltage Controller', 'მერსედეს CLS-Class W218 / E-Class W212 Full LED ფარის ძაბვის რეგულატორი', 'Original OEM Mercedes-Benz Full LED Headlamp Voltage Controller for CLS-Class W218 / E-Class W212. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Full LED ფარის ძაბვის რეგულატორი (CLS-Class W218 / E-Class W212). გარანტირებული ხარისხი და თავსებადობა.', 1, 5, '/parts/2189004406.webp'),
  ('A2189007306', 'Mercedes CLS-Class W218 / E-Class W212 / S-Class W222 LED Power Voltage Converter', 'მერსედეს CLS-Class W218 / E-Class W212 / S-Class W222 LED კვების ძაბვის გარდამქმნელი', 'Original OEM Mercedes-Benz LED Power Voltage Converter for CLS-Class W218 / E-Class W212 / S-Class W222. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED კვების ძაბვის გარდამქმნელი (CLS-Class W218 / E-Class W212 / S-Class W222). გარანტირებული ხარისხი და თავსებადობა.', 1, 5, '/parts/2189007306.webp'),
  ('A2189009103', 'Mercedes CLS-Class W218 / E-Class W212 / S-Class W222 LED Lighting Voltage Converter', 'მერსედეს CLS-Class W218 / E-Class W212 / S-Class W222 LED განათების ძაბვის გარდამქმნელი', 'Original OEM Mercedes-Benz LED Lighting Voltage Converter for CLS-Class W218 / E-Class W212 / S-Class W222. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED განათების ძაბვის გარდამქმნელი (CLS-Class W218 / E-Class W212 / S-Class W222). გარანტირებული ხარისხი და თავსებადობა.', 1, 5, '/parts/2189009103.webp'),
  ('A2189009203-2', 'Mercedes CLS-Class W218 / E-Class W212 / S-Class W222 LED Headlight Voltage Converter Module (Pair Unit)', 'მერსედეს CLS-Class W218 / E-Class W212 / S-Class W222 LED ფარის ძაბვის გარდამქმნელი (მეორე ბლოკი)', 'Original OEM Mercedes-Benz LED Headlight Voltage Converter Module (Pair Unit) for CLS-Class W218 / E-Class W212 / S-Class W222. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED ფარის ძაბვის გარდამქმნელი (მეორე ბლოკი) (CLS-Class W218 / E-Class W212 / S-Class W222). გარანტირებული ხარისხი და თავსებადობა.', 1, 5, '/parts/2189009203%20(2).webp'),
  ('A2189009203', 'Mercedes CLS-Class W218 / E-Class W212 / S-Class W222 LED Headlight Voltage Converter Module', 'მერსედეს CLS-Class W218 / E-Class W212 / S-Class W222 LED ფარის ძაბვის გარდამქმნელი მოდული', 'Original OEM Mercedes-Benz LED Headlight Voltage Converter Module for CLS-Class W218 / E-Class W212 / S-Class W222. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED ფარის ძაბვის გარდამქმნელი მოდული (CLS-Class W218 / E-Class W212 / S-Class W222). გარანტირებული ხარისხი და თავსებადობა.', 1, 5, '/parts/2189009203.webp'),
  ('A2219000701', 'Mercedes S-Class W221 / CL C216 S-Class Xenon / LED Headlamp Controller', 'მერსედეს S-Class W221 / CL C216 S-Class ქსენონ/LED ფარის მართვის მოდული', 'Original OEM Mercedes-Benz S-Class Xenon / LED Headlamp Controller for S-Class W221 / CL C216. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის S-Class ქსენონ/LED ფარის მართვის მოდული (S-Class W221 / CL C216). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2219000701.webp'),
  ('A2228700789', 'Mercedes S-Class W222 / Maybach X222 Full LED Headlight Main Computer', 'მერსედეს S-Class W222 / Maybach X222 Full LED ფარის მთავარი კომპიუტერი', 'Original OEM Mercedes-Benz Full LED Headlight Main Computer for S-Class W222 / Maybach X222. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Full LED ფარის მთავარი კომპიუტერი (S-Class W222 / Maybach X222). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2228700789.webp'),
  ('A2229000515', 'Mercedes S-Class W222 / Maybach X222 Full LED Headlight Control Module', 'მერსედეს S-Class W222 / Maybach X222 Full LED ფარის მართვის მოდული', 'Original OEM Mercedes-Benz Full LED Headlight Control Module for S-Class W222 / Maybach X222. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Full LED ფარის მართვის მოდული (S-Class W222 / Maybach X222). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2229000515.webp'),
  ('A2229004505', 'Mercedes S-Class W222 Facelift / Maybach Multibeam LED Headlight Driver Unit', 'მერსედეს S-Class W222 Facelift / Maybach Multibeam LED ფარის დრაივერის ბლოკი', 'Original OEM Mercedes-Benz Multibeam LED Headlight Driver Unit for S-Class W222 Facelift / Maybach. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Multibeam LED ფარის დრაივერის ბლოკი (S-Class W222 Facelift / Maybach). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2229004505.webp'),
  ('A2229004812', 'Mercedes S-Class W222 Facelift / Maybach Multibeam LED Main Light Controller', 'მერსედეს S-Class W222 Facelift / Maybach Multibeam LED მთავარი განათების მოდული', 'Original OEM Mercedes-Benz Multibeam LED Main Light Controller for S-Class W222 Facelift / Maybach. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Multibeam LED მთავარი განათების მოდული (S-Class W222 Facelift / Maybach). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2229004812.webp'),
  ('A2229008005', 'Mercedes S-Class W222 / Maybach X222 LED Headlamp Control Computer', 'მერსედეს S-Class W222 / Maybach X222 LED ფარის მართვის კომპიუტერი', 'Original OEM Mercedes-Benz LED Headlamp Control Computer for S-Class W222 / Maybach X222. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED ფარის მართვის კომპიუტერი (S-Class W222 / Maybach X222). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2229008005.webp'),
  ('A2229008105', 'Mercedes S-Class W222 / Maybach X222 High-Performance LED Driver Module', 'მერსედეს S-Class W222 / Maybach X222 მაღალი წარმადობის LED დრაივერის მოდული', 'Original OEM Mercedes-Benz High-Performance LED Driver Module for S-Class W222 / Maybach X222. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის მაღალი წარმადობის LED დრაივერის მოდული (S-Class W222 / Maybach X222). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2229008105.webp'),
  ('A2239000020', 'Mercedes S-Class W223 / EQS V297 Digital Light Flagship Control Unit', 'მერსედეს S-Class W223 / EQS V297 Digital Light ფლაგმანური მართვის ბლოკი', 'Original OEM Mercedes-Benz Digital Light Flagship Control Unit for S-Class W223 / EQS V297. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Digital Light ფლაგმანური მართვის ბლოკი (S-Class W223 / EQS V297). გარანტირებული ხარისხი და თავსებადობა.', 1, 2, '/parts/2239000020.webp'),
  ('A2239001521', 'Mercedes S-Class W223 / EQS V297 Digital Light Projection Headlight Computer', 'მერსედეს S-Class W223 / EQS V297 Digital Light პროექციული ფარის კომპიუტერი', 'Original OEM Mercedes-Benz Digital Light Projection Headlight Computer for S-Class W223 / EQS V297. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Digital Light პროექციული ფარის კომპიუტერი (S-Class W223 / EQS V297). გარანტირებული ხარისხი და თავსებადობა.', 1, 2, '/parts/2239001521.webp'),
  ('A2239001615', 'Mercedes S-Class W223 / EQS V297 Digital Light Main Controller Unit', 'მერსედეს S-Class W223 / EQS V297 Digital Light მთავარი მართვის ბლოკი', 'Original OEM Mercedes-Benz Digital Light Main Controller Unit for S-Class W223 / EQS V297. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Digital Light მთავარი მართვის ბლოკი (S-Class W223 / EQS V297). გარანტირებული ხარისხი და თავსებადობა.', 1, 2, '/parts/2239001615.webp'),
  ('A2239002526 / A2239002626', 'Mercedes S-Class W223 / EQS V297 Digital Light Headlamp Control Module Pair', 'მერსედეს S-Class W223 / EQS V297 Digital Light ფარის მართვის მოდულების წყვილი', 'Original OEM Mercedes-Benz Digital Light Headlamp Control Module Pair for S-Class W223 / EQS V297. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Digital Light ფარის მართვის მოდულების წყვილი (S-Class W223 / EQS V297). გარანტირებული ხარისხი და თავსებადობა.', 1, 2, '/parts/2239002526%20%20%202239002626.webp'),
  ('A2239005120 / A2239005220', 'Mercedes S-Class W223 / EQS V297 Digital Light Driver Unit Pair', 'მერსედეს S-Class W223 / EQS V297 Digital Light დრაივერების წყვილი', 'Original OEM Mercedes-Benz Digital Light Driver Unit Pair for S-Class W223 / EQS V297. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Digital Light დრაივერების წყვილი (S-Class W223 / EQS V297). გარანტირებული ხარისხი და თავსებადობა.', 1, 2, '/parts/2239005120%20%20%202239005220.webp'),
  ('A2239005420', 'Mercedes S-Class W223 / EQS V297 Digital Light Lighting Controller', 'მერსედეს S-Class W223 / EQS V297 Digital Light განათების მოდული', 'Original OEM Mercedes-Benz Digital Light Lighting Controller for S-Class W223 / EQS V297. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Digital Light განათების მოდული (S-Class W223 / EQS V297). გარანტირებული ხარისხი და თავსებადობა.', 1, 2, '/parts/2239005420.webp'),
  ('A2239007618', 'Mercedes S-Class W223 / EQS V297 Digital Light Multibeam Computer', 'მერსედეს S-Class W223 / EQS V297 Digital Light Multibeam კომპიუტერი', 'Original OEM Mercedes-Benz Digital Light Multibeam Computer for S-Class W223 / EQS V297. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Digital Light Multibeam კომპიუტერი (S-Class W223 / EQS V297). გარანტირებული ხარისხი და თავსებადობა.', 1, 2, '/parts/2239007618.webp'),
  ('A2239007718', 'Mercedes S-Class W223 / EQS V297 Digital Light Projection Module', 'მერსედეს S-Class W223 / EQS V297 Digital Light პროექციის მოდული', 'Original OEM Mercedes-Benz Digital Light Projection Module for S-Class W223 / EQS V297. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Digital Light პროექციის მოდული (S-Class W223 / EQS V297). გარანტირებული ხარისხი და თავსებადობა.', 1, 2, '/parts/2239007718.webp'),
  ('A2239008527', 'Mercedes S-Class W223 / EQS V297 Digital Light Main Controller Module', 'მერსედეს S-Class W223 / EQS V297 Digital Light მთავარი მართვის მოდული', 'Original OEM Mercedes-Benz Digital Light Main Controller Module for S-Class W223 / EQS V297. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Digital Light მთავარი მართვის მოდული (S-Class W223 / EQS V297). გარანტირებული ხარისხი და თავსებადობა.', 1, 2, '/parts/2239008527.webp'),
  ('A2479004104', 'Mercedes GLA H247 / GLB X247 LED Headlight Control Unit', 'მერსედეს GLA H247 / GLB X247 LED ფარის მართვის მოდული', 'Original OEM Mercedes-Benz LED Headlight Control Unit for GLA H247 / GLB X247. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED ფარის მართვის მოდული (GLA H247 / GLB X247). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2479004104.webp'),
  ('A2479004204', 'Mercedes GLA H247 / GLB X247 LED Headlamp Driver Computer', 'მერსედეს GLA H247 / GLB X247 LED ფარის დრაივერის კომპიუტერი', 'Original OEM Mercedes-Benz LED Headlamp Driver Computer for GLA H247 / GLB X247. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED ფარის დრაივერის კომპიუტერი (GLA H247 / GLB X247). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2479004204.webp'),
  ('A2479004807', 'Mercedes GLA H247 / GLB X247 Multibeam LED Lighting Module', 'მერსედეს GLA H247 / GLB X247 Multibeam LED განათების მოდული', 'Original OEM Mercedes-Benz Multibeam LED Lighting Module for GLA H247 / GLB X247. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Multibeam LED განათების მოდული (GLA H247 / GLB X247). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2479004807.webp'),
  ('A2479004907', 'Mercedes GLA H247 / GLB X247 Multibeam LED Driver Unit', 'მერსედეს GLA H247 / GLB X247 Multibeam LED დრაივერის ბლოკი', 'Original OEM Mercedes-Benz Multibeam LED Driver Unit for GLA H247 / GLB X247. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის Multibeam LED დრაივერის ბლოკი (GLA H247 / GLB X247). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2479004907.webp'),
  ('A2539000700', 'Mercedes GLC X253 / C-Class W205 LED Headlight Control Computer', 'მერსედეს GLC X253 / C-Class W205 LED ფარის მართვის კომპიუტერი', 'Original OEM Mercedes-Benz LED Headlight Control Computer for GLC X253 / C-Class W205. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის LED ფარის მართვის კომპიუტერი (GLC X253 / C-Class W205). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/2539000700.webp'),
  ('A2539050900', 'Mercedes GLC X253 / C-Class W205 GLC Radar Sensor Distronic Unit', 'მერსედეს GLC X253 / C-Class W205 GLC დისტრონიკის რადარის სენსორი', 'Original OEM Mercedes-Benz GLC Radar Sensor Distronic Unit for GLC X253 / C-Class W205. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის GLC დისტრონიკის რადარის სენსორი (GLC X253 / C-Class W205). გარანტირებული ხარისხი და თავსებადობა.', 1, 3, '/parts/2539050900.webp'),
  ('A2539000700-OLD', 'Mercedes GLC X253 Pre-Facelift High-Spec GLC X253 Pre-Facelift High-Spec LED Module', 'მერსედეს GLC X253 Pre-Facelift High-Spec GLC X253 რესტაილინგამდელი LED მოდული', 'Original OEM Mercedes-Benz GLC X253 Pre-Facelift High-Spec LED Module for GLC X253 Pre-Facelift High-Spec. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის GLC X253 რესტაილინგამდელი LED მოდული (GLC X253 Pre-Facelift High-Spec). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/253%E8%80%81%E6%AC%BE%E9%AB%98%E9%85%8D.webp'),
  ('A2059060601', 'Mercedes C-Class W205 Daytime Running Light DRL LED Diode Module', 'მერსედეს C-Class W205 დღის განათების DRL LED დიოდის მოდული', 'Original OEM Mercedes-Benz Daytime Running Light DRL LED Diode Module for C-Class W205. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის დღის განათების DRL LED დიოდის მოდული (C-Class W205). გარანტირებული ხარისხი და თავსებადობა.', 1, 4, '/parts/A2059060601.webp'),
  ('A2189065900', 'Mercedes CLS W218 / E-Class W212 DRL LED Light Control Module', 'მერსედეს CLS W218 / E-Class W212 DRL LED განათების მართვის მოდული', 'Original OEM Mercedes-Benz DRL LED Light Control Module for CLS W218 / E-Class W212. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის DRL LED განათების მართვის მოდული (CLS W218 / E-Class W212). გარანტირებული ხარისხი და თავსებადობა.', 1, 4, '/parts/A2189065900.webp'),
  ('A1779003803-NEW', 'Mercedes A-Class W177 Facelift Multibeam A-Class W177 Facelift Multibeam LED Unit', 'მერსედეს A-Class W177 Facelift Multibeam A-Class W177 რესტაილინგის Multibeam LED ბლოკი', 'Original OEM Mercedes-Benz A-Class W177 Facelift Multibeam LED Unit for A-Class W177 Facelift Multibeam. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის A-Class W177 რესტაილინგის Multibeam LED ბლოკი (A-Class W177 Facelift Multibeam). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/A%E7%BA%A7%20177%E6%96%B0%E6%AC%BE%E5%87%A0%E4%BD%95.webp'),
  ('A2579000100', 'Mercedes CLS-Class C257 Facelift Multibeam CLS C257 Facelift Multibeam LED Module', 'მერსედეს CLS-Class C257 Facelift Multibeam CLS C257 რესტაილინგის Multibeam LED მოდული', 'Original OEM Mercedes-Benz CLS C257 Facelift Multibeam LED Module for CLS-Class C257 Facelift Multibeam. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის CLS C257 რესტაილინგის Multibeam LED მოდული (CLS-Class C257 Facelift Multibeam). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/CLS%20257%E6%96%B0%E6%AC%BE%E5%87%A0%E4%BD%95.webp'),
  ('A2189000000', 'Mercedes CLS-Class W218 Multibeam LED CLS W218 Multibeam LED Control Unit', 'მერსედეს CLS-Class W218 Multibeam LED CLS W218 Multibeam LED მართვის ბლოკი', 'Original OEM Mercedes-Benz CLS W218 Multibeam LED Control Unit for CLS-Class W218 Multibeam LED. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის CLS W218 Multibeam LED მართვის ბლოკი (CLS-Class W218 Multibeam LED). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/CLS%E5%87%A0%E4%BD%95.webp'),
  ('A2059009534-NEW', 'Mercedes C-Class W205 Facelift Multibeam C-Class W205 Facelift Multibeam LED Unit', 'მერსედეს C-Class W205 Facelift Multibeam C-Class W205 რესტაილინგის Multibeam LED ბლოკი', 'Original OEM Mercedes-Benz C-Class W205 Facelift Multibeam LED Unit for C-Class W205 Facelift Multibeam. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის C-Class W205 რესტაილინგის Multibeam LED ბლოკი (C-Class W205 Facelift Multibeam). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/C%E7%BA%A7205%20%E6%96%B0%E6%AC%BE%E5%87%A0%E4%BD%95.webp'),
  ('A2059006805-OLD', 'Mercedes C-Class W205 Pre-Facelift High-Spec C-Class W205 Pre-Facelift LED Module', 'მერსედეს C-Class W205 Pre-Facelift High-Spec C-Class W205 რესტაილინგამდელი LED მოდული', 'Original OEM Mercedes-Benz C-Class W205 Pre-Facelift LED Module for C-Class W205 Pre-Facelift High-Spec. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის C-Class W205 რესტაილინგამდელი LED მოდული (C-Class W205 Pre-Facelift High-Spec). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/C%E7%BA%A7205%20%E8%80%81%E6%AC%BE%E9%AB%98%E9%85%8D.webp'),
  ('A2069007016-METEOR', 'Mercedes C-Class W206 Digital Light Projection C-Class W206 Digital Light Projection Module', 'მერსედეს C-Class W206 Digital Light Projection C-Class W206 Digital Light პროექციული მოდული', 'Original OEM Mercedes-Benz C-Class W206 Digital Light Projection Module for C-Class W206 Digital Light Projection. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის C-Class W206 Digital Light პროექციული მოდული (C-Class W206 Digital Light Projection). გარანტირებული ხარისხი და თავსებადობა.', 1, 2, '/parts/C%E7%BA%A7206%20%E6%B5%81%E6%98%9F%E9%9B%A8.webp'),
  ('A2129008324-OLD', 'Mercedes E-Class W212 Pre-Facelift High-Spec E-Class W212 Pre-Facelift Xenon/LED Unit', 'მერსედეს E-Class W212 Pre-Facelift High-Spec E-Class W212 რესტაილინგამდელი ქსენონ/LED ბლოკი', 'Original OEM Mercedes-Benz E-Class W212 Pre-Facelift Xenon/LED Unit for E-Class W212 Pre-Facelift High-Spec. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის E-Class W212 რესტაილინგამდელი ქსენონ/LED ბლოკი (E-Class W212 Pre-Facelift High-Spec). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/E%E7%BA%A7212%20%E8%80%81%E6%AC%BE%E9%AB%98%E9%85%8D.webp'),
  ('A2139000737-OLD', 'Mercedes E-Class W213 Pre-Facelift Multibeam E-Class W213 Pre-Facelift Multibeam LED Module', 'მერსედეს E-Class W213 Pre-Facelift Multibeam E-Class W213 რესტაილინგამდელი Multibeam LED მოდული', 'Original OEM Mercedes-Benz E-Class W213 Pre-Facelift Multibeam LED Module for E-Class W213 Pre-Facelift Multibeam. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის E-Class W213 რესტაილინგამდელი Multibeam LED მოდული (E-Class W213 Pre-Facelift Multibeam). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/E%E7%BA%A7213%20%E8%80%81%E6%AC%BE%E5%87%A0%E4%BD%95.webp'),
  ('A2479060000', 'Mercedes GLB-Class X247 DRL LED GLB X247 DRL LED Diode Light Source', 'მერსედეს GLB-Class X247 DRL LED GLB X247 DRL LED დიოდური განათება', 'Original OEM Mercedes-Benz GLB X247 DRL LED Diode Light Source for GLB-Class X247 DRL LED. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის GLB X247 DRL LED დიოდური განათება (GLB-Class X247 DRL LED). გარანტირებული ხარისხი და თავსებადობა.', 1, 4, '/parts/GLB%20%E5%85%89%E6%BA%90.webp'),
  ('A2539000700-NEW', 'Mercedes GLC-Class X253 Facelift Multibeam GLC X253 Facelift Multibeam LED Module', 'მერსედეს GLC-Class X253 Facelift Multibeam GLC X253 რესტაილინგის Multibeam LED მოდული', 'Original OEM Mercedes-Benz GLC X253 Facelift Multibeam LED Module for GLC-Class X253 Facelift Multibeam. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის GLC X253 რესტაილინგის Multibeam LED მოდული (GLC-Class X253 Facelift Multibeam). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/GLC%20253%20%E6%96%B0%E6%AC%BE%E5%87%A0%E4%BD%95.webp'),
  ('A1669003309-OLD', 'Mercedes GLE W166 Pre-Facelift High-Spec GLE W166 Pre-Facelift High-Spec LED Unit', 'მერსედეს GLE W166 Pre-Facelift High-Spec GLE W166 რესტაილინგამდელი High-Spec LED ბლოკი', 'Original OEM Mercedes-Benz GLE W166 Pre-Facelift High-Spec LED Unit for GLE W166 Pre-Facelift High-Spec. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის GLE W166 რესტაილინგამდელი High-Spec LED ბლოკი (GLE W166 Pre-Facelift High-Spec). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/GLE%20166%20%E8%80%81%E6%AC%BE%E9%AB%98%E9%85%8D.webp'),
  ('A1679000000', 'Mercedes GLE V167 Facelift Multibeam LED GLE V167 Facelift Multibeam LED Computer', 'მერსედეს GLE V167 Facelift Multibeam LED GLE V167 რესტაილინგის Multibeam LED კომპიუტერი', 'Original OEM Mercedes-Benz GLE V167 Facelift Multibeam LED Computer for GLE V167 Facelift Multibeam LED. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის GLE V167 რესტაილინგის Multibeam LED კომპიუტერი (GLE V167 Facelift Multibeam LED). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/GLE%20167%20%E6%96%B0%E6%AC%BE%E5%87%A0%E4%BD%95.webp'),
  ('A1669003309-GLS', 'Mercedes GLS X166 Pre-Facelift High-Spec GLS X166 Pre-Facelift High-Spec LED Unit', 'მერსედეს GLS X166 Pre-Facelift High-Spec GLS X166 რესტაილინგამდელი High-Spec LED ბლოკი', 'Original OEM Mercedes-Benz GLS X166 Pre-Facelift High-Spec LED Unit for GLS X166 Pre-Facelift High-Spec. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის GLS X166 რესტაილინგამდელი High-Spec LED ბლოკი (GLS X166 Pre-Facelift High-Spec). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/GLS%20166%20%E8%80%81%E6%AC%BE%E9%AB%98%E9%85%8D.webp'),
  ('A1679001111', 'Mercedes GLS X167 Facelift Multibeam LED GLS X167 Facelift Multibeam LED Computer', 'მერსედეს GLS X167 Facelift Multibeam LED GLS X167 რესტაილინგის Multibeam LED კომპიუტერი', 'Original OEM Mercedes-Benz GLS X167 Facelift Multibeam LED Computer for GLS X167 Facelift Multibeam LED. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის GLS X167 რესტაილინგის Multibeam LED კომპიუტერი (GLS X167 Facelift Multibeam LED). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/GLS%20167%20%E6%96%B0%E6%AC%BE%E5%87%A0%E4%BD%95.webp'),
  ('A2229000515-OLD', 'Mercedes S-Class W222 Pre-Facelift High-Spec S-Class W222 Pre-Facelift Full LED Module', 'მერსედეს S-Class W222 Pre-Facelift High-Spec S-Class W222 რესტაილინგამდელი Full LED მოდული', 'Original OEM Mercedes-Benz S-Class W222 Pre-Facelift Full LED Module for S-Class W222 Pre-Facelift High-Spec. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის S-Class W222 რესტაილინგამდელი Full LED მოდული (S-Class W222 Pre-Facelift High-Spec). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/S%E7%BA%A7%20222%E8%80%81%E6%AC%BE%E9%AB%98%E9%85%8D.webp'),
  ('A2229004505-NEW', 'Mercedes S-Class W222 / W223 Multibeam S-Class Multibeam LED Main Headlight Unit', 'მერსედეს S-Class W222 / W223 Multibeam S-Class Multibeam LED მთავარი ფარის ბლოკი', 'Original OEM Mercedes-Benz S-Class Multibeam LED Main Headlight Unit for S-Class W222 / W223 Multibeam. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის S-Class Multibeam LED მთავარი ფარის ბლოკი (S-Class W222 / W223 Multibeam). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/S%E7%BA%A7%E6%96%B0%E6%AC%BE%E5%87%A0%E4%BD%95.webp'),
  ('A2139005035-NEW', 'Mercedes E-Class W213 Facelift Multibeam E-Class W213 Facelift Multibeam LED Computer', 'მერსედეს E-Class W213 Facelift Multibeam E-Class W213 რესტაილინგის Multibeam LED კომპიუტერი', 'Original OEM Mercedes-Benz E-Class W213 Facelift Multibeam LED Computer for E-Class W213 Facelift Multibeam. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის E-Class W213 რესტაილინგის Multibeam LED კომპიუტერი (E-Class W213 Facelift Multibeam). გარანტირებული ხარისხი და თავსებადობა.', 1, 1, '/parts/%E6%96%B0%E6%AC%BEE%E7%BA%A7213%E5%87%A0%E4%BD%95.webp'),
  ('A2229060000', 'Mercedes S-Class W222 Facelift DRL LED S-Class W222 Facelift DRL LED Diode Module', 'მერსედეს S-Class W222 Facelift DRL LED S-Class W222 რესტაილინგის DRL LED დიოდის მოდული', 'Original OEM Mercedes-Benz S-Class W222 Facelift DRL LED Diode Module for S-Class W222 Facelift DRL LED. Genuine factory module with guaranteed performance.', 'ორიგინალი OEM მერსედეს-ბენცის S-Class W222 რესტაილინგის DRL LED დიოდის მოდული (S-Class W222 Facelift DRL LED). გარანტირებული ხარისხი და თავსებადობა.', 1, 4, '/parts/%E6%96%B0%E6%AC%BES%E7%BA%A7%20222%E5%85%89%E6%BA%90.webp')
on conflict (code) do nothing;

