-- This compatibility file is intentionally non-executable.
--
-- The schema is now maintained as ordered migrations in:
--   supabase/migrations/
--
-- For a new or existing Supabase project, apply every migration in filename order,
-- then run supabase/seed_all.sql. See docs/PHASE_1_DATABASE.md.
